apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce        # TODO: hint neeche
  resources:
    requests:
      storage: {{ .Values.db.storage }}