apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==    
  MYSQL_PASSWORD: bm90ZXNwYXNz       
  MYSQL_USER: bm90ZXN1c2Vy      
  MYSQL_DATABASE: bm90ZXNkYg==