apiVersion: v1
kind: Service
metadata:
  name: django-notes
spec:
  type: {{ .Values.notesApp.service.type }}
  selector:
    app: django-notes
  ports:
    - port: {{ .Values.notesApp.service.port }}
      targetPort: {{ .Values.notesApp.containerPort }}