apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: notes-app.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: django-service
                port:
                  number: {{ .Values.django.service.port }}
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: django-service
                port:
                  number: {{ .Values.django.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontend.service.port }}