apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.djangoDB.service.type }}
  selector:
    app: postgres
  ports:
    - port: {{ .Values.djangoDB.service.port }}
      targetPort: 5432